### ISSUE TITLE
Undefined References to rand_r while installing

### ISSUE THREAD

**Issue by ghost** [lisa-lab/pylearn2#914]
Hi,
I am trying to install pylearn2 in windows (Anaconda community edition precisely). The installation breaks while running setup.py develop stating reason as undefined references to rand_r . Is this a known issue with windows/Anaconda or some bug ? 
Here is the stacktrace : 
C:\mywares\Anaconda\MinGW\bin\gcc.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\pylearn2\utils_window_flip.o build\temp.win-amd64-2.7\Release\pylearn2\utils_window_flip.def -LC:\mywares\Anaconda\libs -LC:\mywares\Anaconda\PCbuild\amd64 -lpython27 -lmsvcr90 -o C:\Users\sony\Downloads\pylearn2-master\pylearn2-master\pylearn2\utils_window_flip.pyd
build\temp.win-amd64-2.7\Release\pylearn2\utils_window_flip.o:_window_flip.c:(.
text+0x598a): undefined reference to `rand_r'
build\temp.win-amd64-2.7\Release\pylearn2\utils\_window_flip.o:_window_flip.c:(.
text+0x59ae): undefined reference to`rand_r'
build\temp.win-amd64-2.7\Release\pylearn2\utils_window_flip.o:_window_flip.c:(.
text+0x59d4): undefined reference to `rand_r'
build\temp.win-amd64-2.7\Release\pylearn2\utils\_window_flip.o:_window_flip.c:(.
text+0x77a7): undefined reference to`rand_r'
build\temp.win-amd64-2.7\Release\pylearn2\utils_window_flip.o:_window_flip.c:(.
text+0x77d4): undefined reference to `rand_r'
build\temp.win-amd64-2.7\Release\pylearn2\utils\_window_flip.o:_window_flip.c:(.
text+0x77fc): more undefined references to`rand_r' follow
collect2.exe: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by eyaler** [comment]
I just ran in to this issue with python 3 and needed to apply the fix in the above comment. should we open a new issue for this?

**Comment by lamblin** [comment]
Yes, a new issue would be a good idea.
Or, if that solution also works on Python 2.6, then a pull request implementing that would be even better :)
